name: Sync Labels

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/labels.yml'

jobs:
  sync:
    runs-on: [self-hosted, linux]
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Sync labels
        uses: EndBug/label-sync@7753e99e1e64188c24d7deede343c5a63e7c0d39 # v2.3.3
        with:
          config-file: .github/labels.yml
          delete-other-labels: false
          dry-run: false
